package com.ixigo.HomePage;

public enum EntityStatusCodes {
    NOT_INITIALIZED, OKAY, NETWORK_ERROR, CONNECTION_ERROR, DATA_ERROR, SERVER_ERROR, DB_ERROR, DUPLICATE_REQUEST, NO_RESPONSE, INVALID_USER, MODIFIED;
}
